ALTER TABLE [dbo].[MessageType]
    ADD CONSTRAINT [PK_MessageType] PRIMARY KEY CLUSTERED ([pkID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

