ALTER TABLE [dbo].[Enumeration]
    ADD CONSTRAINT [UQ_Enumeration_Name] UNIQUE NONCLUSTERED ([enumName] ASC, [enumCategory] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

